# This file is part of analysis_tools.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

__all__ = ("CalcPerPatchMetrics",)

from collections.abc import Iterable

import numpy as np

import lsst.pex.config as pexConfig
from lsst.analysis.tools.interfaces import MetricAction

from ...interfaces import KeyedData, KeyedDataAction, KeyedDataSchema, Vector


class CalcPerPatchMetrics(KeyedDataAction):
    """Compute per-patch values of metrics."""

    actions = pexConfig.configurableActions.ConfigurableActionStructField[MetricAction](
        doc="The actions to compute per-patch metrics",
    )
    format = pexConfig.Field[str](
        doc="Format for internal metric keys. Must use {metric} as a template.",
        default="tract_patch_{metric}",
    )
    key_patch = pexConfig.Field[str](doc="Key for the patch index", default="patch")
    key_patch_out = pexConfig.Field[str](
        doc="Key to output for the patch index corresponding to a metric value",
        default="metric_patch_{band}",
    )
    key_tract = pexConfig.Field[str](doc="Key for the tract index", default="tract")
    key_tract_out = pexConfig.Field[str](
        doc="Key to output for the tract index corresponding to a metric value",
        default="metric_tract_{band}",
    )
    metrics = pexConfig.ListField[str](
        doc="List of metrics to output. If None, all will be output.",
        optional=True,
        default=None,
        listCheck=lambda x: (x is None) or len(x) > 0,
    )
    n_patch_min = pexConfig.Field[int](
        doc="Minimum number of points per patch to draw it",
        default=200,
        check=lambda x: x >= 0,
    )

    def finalize(self):
        """Initialize metrics to the full list generated by all actions.

        This is not called automatically; it is a convenience function
        for cases when all metrics are likely to be used. Otherwise,
        only the necessary metric keys should be specified.
        """
        if self.metrics is None:
            metrics = []
            for _, action in self.actions.items():
                metrics.extend([x[0] for x in action.getOutputSchema()])
            self.metrics = metrics

    def getInputSchema(self) -> KeyedDataSchema:
        for _, action in self.actions.items():
            yield from action.getInputSchema()
        yield self.key_patch, Vector
        yield self.key_tract, Vector

    def getOutputSchema(self) -> KeyedDataSchema:
        for metrics in (self.metrics, (self.key_tract_out, self.key_patch_out)):
            for metric in metrics:
                yield self.format.format(metric=metric), Vector

    def __call__(self, data: KeyedData, **kwargs) -> KeyedData:
        band = kwargs.get("band")
        skymapInfo = kwargs["skymap"]
        tract_counts = {k: (v, {}) for k, v in zip(*np.unique(data[self.key_tract], return_counts=True))}

        # key: input name, value: output name
        metrics_formatted = {
            metric.format(band=band): self.format.format(metric=metric).format(band=band)
            for metric in self.metrics
        }
        outputs = {metric_formatted: [] for metric_formatted in metrics_formatted.values()}
        key_tract_out, key_patch_out = (
            self.format.format(metric=key_tp).format(band=band)
            for key_tp in (self.key_tract_out, self.key_patch_out)
        )
        outputs_tract, outputs_patch = [], []
        outputs[key_tract_out], outputs[key_patch_out] = outputs_tract, outputs_patch

        columns = set(v[0] for v in self.getInputSchema())

        for tract, (n_tract, results_border) in tract_counts.items():
            tractInfo = skymapInfo[tract]
            in_tract = data[self.key_tract] == tract

            data_tract = self._subset_data(data, in_tract, columns)

            patch_counts = {k: v for k, v in zip(*np.unique(data_tract[self.key_patch], return_counts=True))}
            in_tracts = {}
            for patch, n_patch in patch_counts.items():
                if n_patch == 0:
                    continue

                n_columns, n_rows = tractInfo.getNumPatches()
                patchInfo = tractInfo[patch]
                column, row = patchInfo.getIndex()

                data_patch = data_tract
                within_patch = None

                # Get the data for the border patch, if any
                if (results := results_border.get(patch)) is None:
                    patches_other = []

                    left, right = column == 0, column == (n_columns - 1)
                    bottom, top = row == 0, row == (n_rows - 1)
                    aside = left or right
                    atop = bottom or top

                    if aside or atop:
                        within_patch = in_tract & (data[self.key_patch] == patch)

                    # The rings skymap is guaranteed to have adjacent patches
                    # with the same dec boundaries but different RA. These
                    # have smaller inner areas than non-boundary patches and
                    # so it's preferable to combine them so they're a similar
                    # area as a non-boundary patch (in fact, for lsst_cells_v2
                    # they're still smaller, but in another skymap they could
                    # end up bigger instead).
                    if aside:
                        bbox = patchInfo._outerBBox
                        # The 100 pixel offset is because there are WCS and
                        # floating point issues with using findTract or
                        # findPatch right at the very edge of a patch's
                        # inner bbox.
                        pos_y = (
                            (bbox.getEndY() - 100)
                            if bottom
                            else ((bbox.getBeginY() + 100) if top else bbox.getCenterY())
                        )
                        pos_x = bbox.getEndX() if right else bbox.getBeginX()
                        if atop:
                            # TODO: figure this out
                            pass
                        tractInfo_other = skymapInfo.findTract(tractInfo.wcs.pixelToSky(pos_x, pos_y))
                        tract_other = tractInfo_other.tract_id
                        column_other = 0 if right else n_columns - 1
                        patch_other = tractInfo_other[column_other, row].getSequentialIndex()
                        patches_other.append((tract_other, patch_other))
                        if (in_tract_other := in_tracts.get(tract_other)) is None:
                            in_tract_other = data[self.key_tract] == tract_other
                            in_tracts[tract_other] = in_tract_other
                        within_patch |= in_tract_other & (data[self.key_patch] == patch_other)
                        data_patch = data
                    elif atop:
                        bbox = patchInfo._innerBBox
                        pos_x = bbox.getCenterX()
                        pos_y = bbox.getEndY() if top else bbox.getBeginY()
                        coord_other = tractInfo.wcs.pixelToSky(pos_x, pos_y)
                        tractInfo_other = skymapInfo.findTract(coord_other)
                        tract_other = tractInfo_other.tract_id
                        column_other = skymapInfo[tract_other].findPatch(coord_other).getIndex()[0]
                        if (column_other == 0) or (column_other == (n_columns - 1)):
                            # TODO: figure this out too
                            within_patch = None
                        else:
                            row_other = 0 if top else n_rows - 1
                            patch_other = tractInfo_other[column_other, row_other].getSequentialIndex()
                            patches_other.append((tract_other, patch_other))
                            if (in_tract_other := in_tracts.get(tract_other)) is None:
                                in_tract_other = data[self.key_tract] == tract_other
                                in_tracts[tract_other] = in_tract_other
                            within_patch |= in_tract_other & (data[self.key_patch] == patch_other)
                            data_patch = data

                if (results is not None) or (n_patch > 0):
                    if results is None:
                        if within_patch is None:
                            within_patch = data_tract[self.key_patch] == patch
                        subset = self._subset_data(data_patch, within_patch, columns)
                        results = {}
                        for _, action in self.actions.items():
                            results.update(action(subset, band=band))
                        tracts_out = [tract]
                        patches_out = [patch]
                        if patches_other:
                            tracts_out += [tp[0] for tp in patches_other]
                            patches_out += [tp[1] for tp in patches_other]
                        for tract_out, patch_out in zip(tracts_out, patches_out):
                            for key_in, key_out in metrics_formatted.items():
                                outputs[key_out].append(results[key_in])
                            outputs_tract.append(tract_out)
                            outputs_patch.append(patch_out)

        outputs = {k: np.array(v) for k, v in outputs.items()}

        return outputs

    def _subset_data(
        self,
        data: KeyedData,
        subset: np.ndarray,
        columns: Iterable[str],
    ) -> KeyedData:
        """Return a subset of a KeyedData from a boolean/index mask.

        Parameters
        ----------
        data
            The data to select a subset of.
        subset
            The subset to select.

        Returns
        -------
        data_subset
            The subset of data.
        """
        try:
            data_subset = data[subset]
        # raises unhashable type: list for dict-like data, which must be
        # supported, not just table-like data
        except TypeError:
            data_subset = {k: data[k][subset] for k in columns}
        return data_subset
