name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

  push:

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Subject Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          pattern: '^.{0,50}(\n.*)*$'
          error: 'Subject too long (max 50)'
      - name: Check Subject Line Capitalization
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          pattern: '^[A-Z]'
          error: 'Subject line must begin with an imperative, capitalized'
      - name: Check Subject Line Ending
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          pattern: '(?<!\.)$'
          error: 'Subject line must not end with a period'
      - name: Check Body Line Length
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          pattern: '^.+(\n.{0,72}\n)*$'
          error: 'Body line too long (max 72)'
      - name: Check that main was not merged
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          pattern: ^(?!Merge branch 'main' into)
          error: 'Ticket branch needs to be rebased onto main'
      - name: Check overall commit Message
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          pattern: '^(?![A-Z].*\.)[A-Z].{0,49}\r?\n\r?\n(?:.{0,71}\r?\n)*(?:.{0,71}\.)?\r?\n?$'
          error: "Something is not right"
